LBicycleRentSystem/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('theSystem.urls', namespace='system')),
    url(r'^search' ,include('haystack.urls')), # 搜索结果页面
]

theSystem/urls.py
from django.conf.urls import url
from theSystem.views import *

urlpatterns = [
    url(r'^register$', Register.as_view(), name='register'),  # 用户注册
    url(r'^login$', LoginView.as_view(), name='login'), # 用户登陆
    url(r'^logout$', LogoutView.as_view(), name='logout'), # 用户登出
    url(r'^active/(?P<token>.*)$', ActiveView.as_view(), name='active'), # 用户激活
    url(r'^user$', UserInfoView.as_view(), name='user'), # 用户个人中心页面
    url(r'^order/(?P<page>\d+)$', OrderView.as_view(), name='order'), # 用户订单页面
    url(r'^site$', SiteView.as_view(), name='site'), # 信息页面
    url(r'^index$', Index.as_view(), name='index'), # 主页
    url(r'^detail/(?P<goods_id>\d+)$', Detail.as_view(), name='detail'), # 商品详情页面
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
    url(r'^add$', CartAddView.as_view(), name='add'), # 购物车添加
    url(r'^cart$', CartInfoView.as_view(), name='cart' ), # 购物车页面
    url(r'^delete$', CartDeleteView.as_view(), name='delete'), # 购物车页面删除功能
    url(r'^updata$', CartUpdateView.as_view(), name='updata'), # 购物车页面数据更新
    url(r'^takeorder$', OrderPlaceView.as_view(), name='takeorder'), # 提交订单页面
    url(r'^ordercommit', OrderCommitView.as_view(), name='ordercommit'), # 结账
    url(r'^show/(?P<order_id>\d+)$', OrderShow.as_view(), name='show'),
    url(r'^new$', New.as_view(), name='new')
]

templates/base.html
{# 首页 注册 登录 #}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{% load staticfiles %}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    {# 网页标题内容块 #}
	<title>{% block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	{# 网页顶部引入文件块 #}
    {% block topfiles %}{% endblock topfiles %}
</head>
<body>
{# 网页顶部欢迎信息块 #}
{% block header_con %}
	<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">

					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
{#					<a href="{% url 'system:logout' %}">退出</a>#}

                <a href="{% url 'system:logout'%}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'system:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'system:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>

                    <a href="{% url 'system:user' %}">用户中心</a>
					<span>|</span>
{#					<a href="{% url 'system:view' %}">我的购物车</a>#}
                    <a href="{% url 'system:cart' %}">管理中心</a>
					<span>|</span>
{#					<a href="{% url 'system:order' %}">我的订单</a>#}
                    <a href="{% url 'system:takeorder' %}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{% endblock header_con %}

{# 网页顶部搜索框块 #}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="{% url 'system:index' %}" class="logo fl"><img src='/static/images/IMG_1.jpg'></a>
		<div class="search_con fl">
              <form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索自行车">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'system:cart' %}" class="cart_name fl">订单管理</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}

{# 网站主体内容块 #}
{% block body %}{% endblock body %}


	{% block bottomfiles %}{% endblock bottomfiles %}
</body>
</html>

templates/baseCenter.html
{# 用户中心3页面 #}
{% extends 'base_no_cart.html' %}
{% block title %}-用户中心-{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
		<div class="left_menu_con clearfix">
			<h3>用户中心</h3>
			<ul>
				<li><a href="{% url 'system:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
				<li><a href="{% url 'system:order' 1 %}" {% if page == 'order' %}class="active"{% endif %}>全部订单</a></li>

				<li><a href="{% url 'system:site' %}" {% if page == 'site' %}class="active"{% endif %}>信息修改</a></li>

			</ul>
		</div>
        {# 用户中心右侧内容块 #}
        {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/base_detail_list.html
{# 详情页 列表页 #}
{% extends 'base.html' %}
{# 网站主体内容块 #}
{% block body %}
	<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
{#					<li><a href="{% url 'system:list' type.id 1 %}" >{{ type.goods }}</a></li>#}
                        <li><a href="#" >{{ type.brand }}</a></li>
					{% endfor %}
				</ul>
			</div>
		</div>
	</div>
    {# 详情页，列表页主体内容块 #}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}

templates/detail.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}-自行车详情-{% endblock title %}

{% block main_content %}
	<div class="breadcrumb">
		<a href="{% url 'system:index' %}">全部分类</a>
		<span>></span>
		<a href="{% url 'system:list' brand.id 1 %}">{{brand.brand }}</a>
		<span>></span>
		<a href="#">自行车详情</a>
	</div>

	<div class="goods_detail_con clearfix">
		<div class="goods_detail_pic fl"><img src="{% static sku.img %}"></div>

		<div class="goods_detail_list fr">
			<h3>{{ sku.goods }}</h3>
			<h3>库存:{{ sku.goodsNum }}</h3>
			<div class="prize_bar">
				<span class="show_pirze">¥<em>{{ sku.price }}</em></span>
			</div>
			<div class="goods_num clearfix">
				<div class="num_name fl">数 量：</div>
				<div class="num_add fl">
					<input type="text" class="num_show fl" value="1">
					<a href="javascript:;" class="add fr">+</a>
					<a href="javascript:;" class="minus fr">-</a>
				</div>
			</div>
			<div class="total">总价：<em>10元</em></div>
			<div class="operate_btn">
                {% csrf_token %}
{#                <form method="post" action="/new">#}

{#				<a href="{% url 'system:new' %}" sku_id="{{ sku.id }}" count ='1' class="buy_btn">立即租赁</a>#}
{#                <li>#}
{#                    <input class="buy_btn" type="submit" value="立即租赁">#}
{#                </li>#}
{#                </form><br>#}

				<a href="javascript:;" sku_id="{{ sku.id }}" count="1" class="add_cart" id="add_cart">租赁自行车</a>
			</div>

		</div>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">

		</div>

		<div class="r_wrap fr clearfix">

		</div>
	</div>
{% endblock main_content %}
{% block bottom %}
	<div class="add_jump"></div>
{% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
        update_goods_amount()
        // 计算商品的总价格
        function update_goods_amount() {
            // 获取商品的单价和数量
            price = $('.show_pirze').children('em').text()
            count = $('.num_show').val()
            // 计算商品的总价
            price = parseFloat(price)
            count = parseInt(count)
            amount = price*count
            // 设置商品的总价
            $('.total').children('em').text(amount.toFixed(2)+'元')
        }

        // 增加商品的数量
        $('.add').click(function () {
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 加1
            count = parseInt(count)+1
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 减少商品的数量
        $('.minus').click(function () {
            // 获取商品原有的数目
            count = $('.num_show').val()
            // 减1
            count = parseInt(count)-1
            if (count <= 0){
                count = 1
            }
            // 重新设置商品的数目
            $('.num_show').val(count)
            // 更新商品的总价
            update_goods_amount()
        })

        // 手动输入商品的数量
        $('.num_show').blur(function () {
            // 获取用户输入的数目
            count = $(this).val()
            // 校验count是否合法
            if (isNaN(count) || count.trim().length==0 || parseInt(count) <=0){
                count = 1
            }
            // 重新设置商品的数目
            $(this).val(parseInt(count))
            // 更新商品的总价
            update_goods_amount()
        })

        // 获取add_cart div元素左上角的坐标
		var $add_x = $('#add_cart').offset().top;
		var $add_y = $('#add_cart').offset().left;

        // 获取show_count div元素左上角的坐标
		var $to_x = $('#show_count').offset().top;
		var $to_y = $('#show_count').offset().left;


		$('#add_cart').click(function(){
            // 获取商品id和商品数量
            sku_id = $(this).attr('sku_id') // attr prop
            count = $('.num_show').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('/add', params, function (data) {
                if (data.res == 5){
                    // 添加成功
                     alert('选定成功，您如果心仪，可以在订单管理下单租赁')
                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数
                                $('#show_count').html(data.total_count);
                            });
			        });
                }
                else{
                    // 添加失败
                    alert(data.errmsg)
                }
            })
		})
        $('#buy_btn').click(function(){
            // 获取商品id和商品数量
            sku_id = $(this).attr('sku_id') // attr prop
            count = $('.num_show').val()
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // 组织参数
            params = {'sku_id':sku_id, 'count':count, 'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/cart/add, 传递参数:sku_id count
            $.post('/new', params, function (data) {
                if (data.res == 5){
                    // 添加成功

                    $(".add_jump").css({'left':$add_y+80,'top':$add_x+10,'display':'block'})
                    $(".add_jump").stop().animate({
                        'left': $to_y+7,
                        'top': $to_x+7},
                        "fast", function() {
                            $(".add_jump").fadeOut('fast',function(){
                                // 重新设置用户购物车中商品的条目数

                                $('#show_count').html(data.total_count);
                            });
                            window.location.href='/cart';
			        });
                }
                else{
                    // 添加失败
                    alert(data.errmsg)
                }
            })
		})
	</script>
{% endblock bottomfiles %}

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}-首页-{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
{#	<div class="navbar_con">#}
{#		<div class="navbar">#}
{#			<h1 class="fl">全部商品分类</h1>#}
{#		</div>#}
{#	</div>#}
{##}
{#	<div class="center_con clearfix">#}
{#		<ul class="subnav fl">#}
{#            {% for type in types %}#}
{#			    <li><a href="#model0{{ forloop.counter }}" >{{ type.brand }}</a></li>#}
{#            {% endfor %}#}
{#		</ul>#}
{##}
{##}
{#	</div>#}

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.brand }}</h3>
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#                {% for banner in type.good %}#}
{#				    <a href="{% url 'goods:detail' banner.id  %}">{{ banner.goods}}</a>#}
{#				{% endfor %}#}
{#			</div>#}
			<a href="{% url 'system:list' type.id 1 %}" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%  static type.img %}  "></div>
			<ul class="goods_list fl">
                {% for banner in type.good %}
				<li>
					<h4><a href="{% url 'system:detail' banner.id  %}">{{ banner.goods }}</a></h4>
					<a href="{% url 'system:detail' banner.id  %}"><img src="{% static banner.img %}"></a>
					<div class="prize">¥ {{ banner.price }}/小时</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/list.html
{% extends 'base_detail_list.html' %}
{% load staticfiles %}
{% block title %}-自行车列表-{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="{% url 'system:index' %}">全部分类</a>
		<span>></span>
		<a href="#">{{ type.brand }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
{#				<h3>新品推荐</h3>#}
{#				<ul>#}
{#                    {% for sku in new_skus %}#}
{#					<li>#}
{#						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>#}
{#						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>#}
{#						<div class="prize">￥{{ sku.price }}</div>#}
{#					</li>#}
{#                    {% endfor %}#}
{#				</ul>#}
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'system:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'system:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'system:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'system:detail' sku.id %}"><img src="{% static sku.img %}"></a>
					<h4><a href="{% url 'system:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price}}/小时</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'system:list' type.id skus_page.previous_page_number %}?sort={{ sort }}">上一页</a>
                {% endif %}
                {% for pindex in skus_page.paginator.page_range %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'system:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'system:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'system:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

templates/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}-登录-{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/IMG_1156[1].jpg' %}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">享受城市之风</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'system:register' %}">立即注册</a>
				</div>
				<div class="form_input">
                    {# 不设置表单action时，提交表单时，会向浏览器地址栏中的地址提交数据 #}
					<form method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
    {{ errmsg }}
{% endblock body %}

templates/register.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}-注册-{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/register.js' %}"></script>
{% endblock topfiles %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="{% static 'images/logo02.png' %}"></a>
			<div class="reg_slogan">选我所选  ·  快乐骑行</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'system:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email">
						<span class="error_tip">提示信息</span>
					</li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”天天生鲜用户使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="submit" value="注 册" name="">
					</li>
				</ul>
				</form>
                {{ errmsg }}
			</div>

		</div>

	</div>
{% endblock body %}

templates/static_index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}-首页-{% endblock title %}
{% block topfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'js/slide.js' %}"></script>
{% endblock topfiles %}
{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" >{{ type.brand }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">

				    <li><img src="" alt="幻灯片"></li>
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">

			    <img src="">
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.brand }}</h3>
{#			<div class="subtitle fl">#}
{#				<span>|</span>#}
{#                {% for banner in type.good %}#}
{#				    <a href="{% url 'goods:detail' banner.id  %}">{{ banner.goods}}</a>#}
{#				{% endfor %}#}
{#			</div>#}
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{%  static type.img %}  "></div>
			<ul class="goods_list fl">
                {% for banner in type.good %}
				<li>
					<h4><a href="{% url 'system:detail' banner.id  %}">{{ banner.good }}</a></h4>
					<a href="{% url 'system:detail' banner.id  %}"><img src="{% static banner.img %}"></a>
					<div class="prize">¥ {{ banner.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

templates/user_center_info.html
{% extends 'baseCenter.html' %}
{% load staticfiles %}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
                            {% if userInfo %}
							<li><span>用户名：</span>{{ userInfo.NickName }}<span>{% if userInfo.gender %}</span><em>先生</em>{% else %}<em>小姐</em>{% endif %}</li>
                                <li><span>联系方式：</span>{{ userInfo.Phone }}</li>
                                <li><span>身份证号码：</span>{{ userInfo.IdCard }}</li>
                            {% else %}
                                <li><span>用户名:</span>{{ user.username }}</li>
                                <li><span>联系方式：</span>无默认</li>
							    <li><span>身份证：</span>无默认</li>
                            {% endif %}
						</ul>
				</div>

				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for good in goods_li %}
                            {% if good %}
                                <li>
        {#                            <a href="{% url 'system:detail' good.id %"><img src="{{ goods.image.url }}"></a>#}
                                    <a href="{% url 'system:detail' good.id %}"><img src="{% static good.img %}"></a>
        {#                            <h4><a href="{% url 'system:detail' good.id %}">{{ goods.name }}</a></h4>#}
                                     <h4><a href="{% url 'system:detail' good.id %}">{{ good.goods }}</a></h4>
                                    <div class="operate">
                                        <span class="prize">￥{{ good.price }}</span>
                                        <a href="#" class="add_goods" title="加入购物车"></a>
                                    </div>
                                </li>
                            {% endif %}
                        {% empty %}
                            无历史浏览记录
                        {% endfor %}
			        </ul>
		        </div>
		</div>
{% endblock right_content %}

templates/user_order_info.html
{% extends 'baseCenter.html' %}
{% load staticfiles %}
{% block right_content %}
		<div class="right_content clearfix">
                {% csrf_token %}
				<h3 class="common_title2">全部订单</h3>
                {% for order in order_page %}
				<ul class="order_list_th w978 clearfix">
					<li class="col01">{{ order.time }}</li>
					<li class="col02">订单号：{{ order.id }}</li>
				</ul>

				<table class="order_list_table w980">
					<tbody>
						<tr>
							<td width="15%"><a href="{% url 'system:show' order.id %}"  class="oper_btn">去付款</a></td>
						</tr>
					</tbody>
				</table>
				{% endfor %}
				<div class="pagenation">
                    {% if order_page.has_previous_page %}
					<a href="{% url 'user:order' order_page.previous_page_number %}">上一页</a>
                    {% endif %}
                    {% for pindex in pages %}
                        {% if pindex == order_page.number %}
					        <a href="{% url 'system:order' pindex %}" class="active">{{ pindex }}</a>
                        {% else %}
					        <a href="{% url 'system:order' pindex %}">{{ pindex }}</a>
                        {% endif %}
					{% endfor %}
                    {% if order_page.has_next_page %}
					<a href="{% url 'system:order' order_page.next_page_number %}">下一页></a>
                    {% endif %}
				</div>
		</div>
{% endblock right_content %}
{#{% block bottomfiles %}#}
{#    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>#}
{#    <script>#}
{#    $('.oper_btn').click(function () {#}
{#        #}
{#        #}
{#       #}
{#        // 进行支付#}
{#        // 获取订单id#}
{#        order_id = $(this).attr('order_id')#}
{#        csrf = $('input[name="csrfmiddlewaretoken"]').val()#}
{#        // 组织参数#}
{#        params = {'order_id':order_id, 'csrfmiddlewaretoken':csrf}#}
{#        // 发起ajax post请求，访问/order/pay, 传递参数:order_id#}
{#        $.post('/show', params, function (data) {#}
{#            if (data.res == 3){#}
{#                // 引导用户到支付页面#}
{#                window.open(data.pay_url)#}
{#            }#}
{#            else{#}
{#                alert(data.errmsg)#}
{#            }#}
{#        })#}
{#     #}
{#    })#}
{#    </script>#}
{#{% endblock bottomfiles %}#}